### ISSUE TITLE
Dots in list of acronym

### ISSUE THREAD

**Issue by larapq** [oetiker/acronym#24]
I have been using your package for a year. In september the list of acronyms was shown correctly. However, with this version , if the acronym was used in a caption two weird things happen when listing the acronyms:
- Two dots appear after each of those elements
- These elements are linked to the list of figures. That is, there is a link from the list of acronyms to the element in the list of figures where the element was used.

**Comment by marsmee** [comment]
Hello @laralennon,

the second issue you describe is the "normal behaviour", because the acronym is actually expanded in the list of figures as it is the first occurrence in the document. So it is absolutely correct that the link in the list of acronyms leads to the list of figures. To prevent this you should use something like: `\caption[\acs{A}]{\acf{A}}`. I will have a look at the first issue when I am at home. In the meantime, could you please provide an MWE and a screenshot of this?

**Comment by marsmee** [comment]
No info provided and could not reproduce the described erroneous behaviour.
