### ISSUE TITLE
Acronyms in TeX Live version 2020 (Overleaf)

### ISSUE THREAD

**Issue by hsteinbrecher** [oetiker/acronym#44]
I am using your package acronym within the overleaf web interface and ran in the following problem. When I compile my file in the TeX Live version 2019 everything works perfectly fine but under the 2020 version the following appears:

Hyper reference `acro:MPC' on page 1 undefined on input line 2.

The error can be reproduced very well with Overleaf's template: https://de.overleaf.com/latex/examples/automatic-acronym-list-in-latex/dzvxfzpsjrmm

Is the problem known or any fix?

**Comment by marsmee** [comment]
Did you define the acronym anywhere? In the template is an additional file included: `\input{acro_list}`.

**Comment by hsteinbrecher** [comment]
Sure, I included the list of acronyms in the way you proposed. The separate tex-file looks the following, but the problem keeps the same:

\begin{acronym}
\acro{BLA}[BLA]{BLABLA}
\end{acronym}

**Comment by marsmee** [comment]
Does it make any difference if you paste the acronym definitions directly into the main document or use `\include`. A temporary fix could be disabling hyperlinks at all with the `nohyperlinks` option, so you can continue your work until we've investigated the issue.

**Comment by hsteinbrecher** [comment]
\include or pasting it directly in the document doesn't make any difference. nohyperlinks reduces the number of warnings but still die list of abbreviations exhibits a much larger line spacing than before. Could you reproduce the error?

**Comment by marsmee** [comment]
I'm currently not at my workstation (and I don't have an Overleaf account). Therefore, two more suggestions just to sort out some error sources. Can you verify the platform uses the latest version `1.47`? Something like this `\expandafter\show\csname ver@acronym.sty\endcsname` could do the trick. Try to use `noacroprefix` if there is an older version. Second, you did not use the longest acronym for spacing (`\begin{acronym}[LONGEST]`) in the code snippet, which could lead to a messed up list.

Additionally, can you provide a screenshot of the erroneous output and the main file including the list of acronyms, please.

**Comment by hsteinbrecher** [comment]
Relating to the version used by overleaf it says: 
Package: acronym 2020/04/17 v1.47 Support for acronyms (Tobias Oetiker) in the log file. 

In the log file it furthermore reports: 
Package acronym Info: Label `acro:IfK' newly defined as it shall be overriddenalthough it is yet undefined on input line 7.

On the second issue relating the messed up list did including \begin{acronym}[LONGEST] do the trick. Thanks for that hint!

**Comment by marsmee** [comment]
So, I've taken a look into this and found out that this warning is well-known, harmless, and caused by the forward linking introduced back in 2020. If an acronym is never fully expanded in the document, no label is generated and the hyperlink goes nowhere; that's it. The issue has already been discussed in https://github.com/oetiker/acronym/issues/32#issuecomment-721042685 + https://github.com/oetiker/acronym/issues/32#issuecomment-722365302 and my mind about it hasn't change: It's a minor bug that doesn't affect the output. I still have ambitions to fix this while refactoring major portions of the package to produce a more extendable and customisable solution.
To get rid of the warning you can use the first solution provided in https://github.com/oetiker/acronym/issues/32#issuecomment-613315836 or just use either the `nohyperlinks` or `printonlyused` option.

**Comment by LuxDei10** [comment]
I also like the old behavior best, so I tried to come up with some kind of workaround. It is by all means no perfect solution but it gets rid of the forward linking and also allows only using the short form.

\usepackage[nohyperlinks]{acronym}

\newcommand{\abkdef}[3]{\acro{#1}[#2]{#3} \label{#1}}
\newcommand{\abks}[1]{\hyperref[#1]{\acs{#1}}}
\newcommand{\abk}[1]{\hyperref[#1]{\ac{#1}}}
\newcommand{\abkl}[1]{\hyperref[#1]{\acl{#1}}}

With these I can define my abbreviations as bevor using \abkdef and refer to them using the \abk, \abks, \abkl commands .

If there is an even better solution let me know.
