### ISSUE TITLE
Upper case ignored for acronyms defined using \acroplural

### ISSUE THREAD

**Issue by b10n** [oetiker/acronym#53]
If an acronym is defined using `\acroplural`, the commands `\Acp`, `\Acfp`, and `\Aclp` fail to capitalize the first letter of the long form.

### MWE
```
\documentclass{article}
\usepackage[nolist]{acronym}

\begin{document}

\begin{acronym}
	\acroplural{AS}[ASes]{autonomous systems}
\end{acronym}

\Acp{AS} \\
\Acfp{AS} \\
\Aclp{AS} \\

\end{document}
```

### Result
> autonomous systems (ASes)
autonomous systems (ASes)
autonomous systems

### Expected result
> Autonomous systems (ASes)
Autonomous systems (ASes)
Autonomous systems

I'm using acronym 2020/04/17 v1.47

**Comment by ProbstDJakob** [comment]
The PR https://github.com/oetiker/acronym/pull/46 has fixed it but there has been no release since (https://ctan.org/pkg/acronym is still on version 1.47).
@oetiker could you please publish the latest releases or is this a problem with TeX Live (or whatever TeX distribution used) not updating their version?

**Comment by oetiker** [comment]
yes will do :)

**Comment by oetiker** [comment]
pushed 1.49 to ctan
